name: Create Release
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        rust-version: [stable]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create release
        uses: elgohr/Github-Release-Action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          title: Release ${{ github.ref }}
